name: JsonCsvConverter CI

on: push

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install all dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm t
